# fizzbuzz　課題1
ito-soichro/fizzbuzz-Ito pull request #1
Opened 2021-01-06 00:28 UTC by ito-soichro

レビューをお願いします！
テストの実装は、`npm t`コマンドで実装出来ます。

```
テストが正しく書けているか？
カバレッジC0で100％か？
テストが全部成功するか？
GitHubに成果物がmasterブランチで提出できているか？
yarn startで1から100までプリントできるか？
```

2021-01-06 01:06 UTC, izumix03 requested changes
□時間内に達成するように計画、実行できたか: OK!!
■テストが正しく書けているか？: コメントしましたのでご確認お願いします🙇
□GitHubに成果物がmasterブランチで提出できているか？: OK!!
□yarn startで1から100までプリントできるか？: OK!!
■カバレッジC0で100％か？: NG...
□テストが全部成功するか？: OK!!

$ jest --coverage
 PASS  src/__tests__/index.test.ts
  1から100を出力
    ✓ count 1 to 100 (9 ms)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.022 s
Ran all test suites.
✨  Done in 1.54s.

2021-01-06 03:37 UTC, izumix03 requested changes
□時間内に達成するように計画、実行できたか: OK!!
■テストが正しく書けているか？: コメントしましたのでご確認お願いします🙇
□GitHubに成果物がmasterブランチで提出できているか？: OK!!
□yarn startで1から100までプリントできるか？: OK!!
■カバレッジC0で100％か？: OK!!(ただしテストが通っていないため修正が必要)
■テストが全部成功するか？: OK!!(ただしテストが通っていないため修正が必要)

2021-01-06 03:37 UTC, izumix03 commented on src/__tests__/index.test.ts
> +        expect(count).toBe(num);
[must]
このテスト全体は以下に書き換えられそうです。
`expect(count).toBe(101);`

ですが、実は `num <= 100` の条件のループなので、
この行は実行されていないと思います。

サンプルのコードを載せてみます。
下記も改善余地はありますので、ぜひ確認お願いします。

```typescript
    const spyLog = jest.spyOn(console, 'log')
    printOneToHundred()
    expect(spyLog.mock.calls).toHaveLength(100)
    Array.from(Array(100).keys()).forEach((i) => {
      expect(spyLog.mock.calls[i]?.[0]).toBe(i + 1)
    })
    spyLog.mockReset()
    spyLog.mockRestore()
```

単体テストのイメージを掴むまで難しいと思いますが、
身につけると力になるのでぜひ頑張りましょう！

2021-01-06 03:37 UTC, izumix03 commented on src/__tests__/index.test.ts
> +describe('1から100を出力', () => {
describe使っているの素晴らしいですね！
今回は1テストだけですが、例えば同じ関数で複数のテストケースを実装する場合は重宝すると思います。

2021-01-06 08:28 UTC, izumix03 requested changes

2021-01-06 08:28 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    expect(array).toHaveLength(100)
とても面白いと思います！

ただ、これですと途中に5000などが入っても成功となるため、
テストとしては不十分かもしれません。

arrayから結果の配列を取り出して操作する場合、以下で必要十分になりますでしょうか？
※抜けがあれば申し訳ありません。
・長さが100
・重複がない
・最小値が1
・最大値が100
・昇順ソートして比較しても同じ(1から順になっている)
・各要素がnumberである(小数などがない)

2021-01-06 08:28 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    printOneToHundred()
[IMO]
こちらのテストですと
printOneToHundred の戻り値は不要かもしれませんがいかがでしょうか？

2021-01-06 08:59 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +    expect(array).toHaveLength(100)
fix_index.test.ts 3にて修正いたしました！

いかがでしょうか？

2021-01-06 08:59 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +    printOneToHundred()
結論としては、削除してしまうとエラーが出てしまいました。

`const spyLog = jest.spyOn(console, 'log')`を記述しているため、確かに必要ないかのとは思いましたが、
.toHaveLengthや.toBe時点でエラーが起こってしまいます。

いかがでしょうか?

2021-01-06 10:42 UTC, izumix03 requested changes
□時間内に達成するように計画、実行できたか: OK!!
■テストが正しく書けているか？: コメントしましたのでご確認お願いします🙇内容理解して頂ければOKです！
□GitHubに成果物がmasterブランチで提出できているか？: OK!!
□yarn startで1から100までプリントできるか？: OK!!
□カバレッジC0で100％か？: OK!!
□テストが全部成功するか？: OK!!

2021-01-06 10:42 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    expect(typeof array).toEqual('object')
[nits]
なるほどです。
適当な提案をしてしまい申し訳ありません。

arrayは配列だと思うのですが、
array[0][0] ~ array[99][0] が全部整数だと保証できるかなと思った次第です:bow:

※全部テストしてもループ回数という意味では同じですがforEachではなく every などが使えます

例えばこんなイメージです。

```
  test('count 1 to 100', () => {
    const spyLog = jest.spyOn(console, 'log')
    printOneToHundred()

    // 全部を配列に詰め直してみます
    const actual = spyLog.mock.calls.map((arr) => arr[0])

    // 要素数は100
    expect(actual).toHaveLength(100)
    // 一意な要素数も100
    expect(new Set(actual).size).toBe(100)

    // 最小は0
    expect(Math.min(...actual)).toBe(1)
    // 最大は100
    expect(Math.max(...actual)).toBe(100)

    // 全部整数
    expect(actual.every((arg) => Number.isInteger(arg))).toBeTruthy()

    // 昇順ソートされている
    expect(actual).toEqual(actual.slice().sort((a, b) => a - b))

    spyLog.mockReset()
    spyLog.mockRestore()
  });
```

2021-01-06 10:42 UTC, izumix03 commented on src/index.ts
> +  return num;
ここを削除するだけでOKです:star:

2021-01-06 10:45 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    printOneToHundred()
[謝罪]
申し訳ありません。
誤解を与えたかもしれません。

index.tsの return num  が不要そうという指摘になります。
[参考: 戻り値とは？](https://www.sejuku.net/blog/28728)

2021-01-06 10:45 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    printOneToHundred()
逆に戻り値がある場合は、
```
const result = printOneToHundred()
```
などとして、戻り値をテストする必要があります:star:

2021-01-06 10:46 UTC, izumix03 commented on src/__tests__/index.test.ts
> +    expect(array).toHaveLength(100)
なるほどです！
ちょっと今回サンプルを書いてみたのでご確認お願いします。

2021-01-07 05:27 UTC, ito-soichro commented on src/index.ts
> +  return num;
修正しました！

コミット[fix_index.ts 2]の内容です！

2021-01-07 06:18 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +    expect(typeof array).toEqual('object')
修正いたしました！

コミット[fix_index.test.ts 6]の内容です！

2021-01-07 06:39 UTC, yukishima-b commented on src/__tests__/index.test.ts
> +const arr = Array.from(Array(100).keys()).map((i) => i+1);
[IMO]
arg/arrのどちらもグローバルになっちゃうので `test` のブロックに入れるとよいかもです！
（それぞれの変数を参照できるところを限る方が見やすいというメリットがあります！）

https://jsprimer.net/basic/function-scope/
```
  test('count 1 to 100', () => {
    const spyLog = jest.spyOn(console, 'log')
    // 他の処理....
  });
``

2021-01-07 06:39 UTC, yukishima-b commented on src/__tests__/index.test.ts
> +    expect(arg).toEqual(arr)
このtoEqualは効率的でいいですね！

2021-01-07 06:49 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +const arr = Array.from(Array(100).keys()).map((i) => i+1);
参考記事ありがとうございます！

修正いたしました！
[こちらです！](https://github.com/ito-soichro/fizzbuzz-Ito/pull/1/commits/e8a8db3fd74ed3119b517f41737abec04490838d)

2021-01-07 06:53 UTC, yukishima-b commented on src/__tests__/index.test.ts
> +    const arg = spyLog.mock.calls.map((arr) => arr[0])
修正ありがとうございます！
この辺はグローバルスコープのままにしてるのって意図があったりしますか？？
```
    const spyLog = jest.spyOn(console, 'log')
    printOneToHundred()
```

2021-01-07 08:39 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +    const arg = spyLog.mock.calls.map((arr) => arr[0])
こちらは、特にグローバル変数であっても無くてもあまり影響は無いと考えました。
どちらかといえば、index.tsファイルの処理をインポートしモックした様な変数は、どこでも使える様にしといた方が、実際の現場でも参照等がしやすいのでは？と考えたためグローバル変数にしております。

例えば、前回のコメントでご指定き頂いた下記二つの記述は、一部のテストを実装するためだけに定義した変数なので、確かにグローバル変数でない方が良いなという考えの元で修正いたしました！
```
const arg = spyLog.mock.calls.map((arr) => arr[0])
const arr = Array.from(Array(100).keys()).map((i) => i+1);
```

いかがでしょうか？

2021-01-07 09:17 UTC, kodaiseto commented on src/__tests__/index.test.ts
> +    const arg = spyLog.mock.calls.map((arr) => arr[0])
意図があってテストを記載しているのが素晴らしいと思います。
記載いただいたコメントに対して返答するとしたら下記のような形になります。

##  spyLogのグローバル化について
`const spyLog = jest.spyOn(console, 'log')`

上記については、メリットデメリットあるかと思います。
それぞれ記載します。
- メリット
```
記載いただいた通りでグローバル変数は使い回しやすいため、
他のテストを追加で作成する際もそのまま利用できる
``` 

- デメリット
```
出力された状態が正しい物なのかどうか、全てのソースをみないとわからない。
``` 
デメリット部分について説明します。
spyLogを他のテストで使い回す場合、
下記が実行されないと spyLogの初期化がされません。
(試してみてください！！)
```   
 spyLog.mockReset()
 spyLog.mockRestore()
```

すると、
他のテストで利用したいにもかかわらず`1から100を出力`でマウントされた値がspyLogに残り続けます。
本来意図した挙動にならない可能性があるということです。

今回テストは1個しかありませんが、
100個テストがあった場合はいかがでしょうか。

100個全てでリセット処理を実行する必要があります。
では、30個目のテストでリセット処理が漏れていた場合はいかがでしょうか。

少なくともリセット処理が漏れているかどうかを確認するために
30個程度テストのソースコードを読まなければいけない可能性があります。

実務では、これがとても辛いです。
不具合があるかどうかを確認するために読むべきソースコードは出来る限り少ない方がいいです。
テストにおいても同様だと考えます。

特にテストにおいては使いやすさよりも正確性、信頼性が求められるんじゃないかなと思うので、
グローバル変数の利用は出来る限り避けるべきかと思います。

##  printOneToHundredのグローバル化について
これはspyLogのようにクリティカルに状態を持たないのでそこまで意識する必要もないと思いますが、
逆にいうと、グローバルにする必要も感じません。

なぜかというと、
他のテストを書くときにprintOneToHundredを実行したことを前提とすることがなさそうだからです。

他のテスト書くときに、printOneToHundredで1 ~ 100を実行する必要があるケースってそんなないと思うのと、
あるのであれば、`1から100を出力`のところに書けばいいと思うので、
影響範囲的な観点でいうと別に必要ないかなという所感です。
もしグローバル化する必要があった場合、初めて、考慮すればよいかなというくらいですかね。

長々と記載しましたが、
指摘に対して意図のある修正をすることはとても良いことだと思いました。

2021-01-07 09:19 UTC, kodaiseto commented on src/__tests__/index.test.ts
> +    const arg = spyLog.mock.calls.map((arr) => arr[0])
> printOneToHundredのグローバル化について
こっちについて指摘としてはnits(細かい指摘(nitpick))程度です！

2021-01-07 09:29 UTC, ito-soichro commented on src/__tests__/index.test.ts
> +    const arg = spyLog.mock.calls.map((arr) => arr[0])
なるほどです！

大変勉強になりました！

上記踏まえて、修正いたしました！

ご確認よろしくお願いいたします！

**fix_index.test.ts 8**
https://github.com/ito-soichro/fizzbuzz-Ito/pull/1/commits/919986406ed4d79330f6fc47baac4887ed529c88

2021-01-07 09:54 UTC, kodaiseto commented
下記の通り、課題1-1達成です！
お疲れ様です！！

□時間内に達成するように計画、実行できたか: OK!!
□テストが正しく書けているか？: OK!!
□GitHubに成果物がmasterブランチで提出できているか？: OK!!
□yarn startで1から100までプリントできるか？: OK!!
□カバレッジC0で100％か？: OK!!
□テストが全部成功するか？: OK!!

次の課題に着手してください！

2021-01-07 11:46 UTC, merged